
[test]
# Load these modules before running tests.
preload = ["./test-setup.ts"]
coverageReporter = ["text", "lcov"] # default ["text"]
# To require 99% line-level and function-level coverage
coverageThreshold = 0.99
